export const cedaCategories = [
  "Abrasive product manufacturing",
  "Accommodation",
  "Accounting, tax preparation, bookkeeping, and payroll services",
  "Adhesive manufacturing",
  "Advertising, public relations, and related services",
  "Air and gas compressor manufacturing",
  "Air conditioning, refrigeration, and warm air heating equipment manufacturing",
  "Air transportation",
  "Aircraft engine and engine parts manufacturing",
  "Aircraft manufacturing",
  "All other chemical product and preparation manufacturing",
  "All other converted paper product manufacturing",
  "All other food and drinking places",
  "All other food manufacturing",
  "All other forging, stamping, and sintering",
  "All other miscellaneous electrical equipment and component manufacturing",
  "All other miscellaneous manufacturing",
  "All other miscellaneous professional, scientific, and technical services",
  "All other retail",
  "All other transportation equipment manufacturing",
  "All other wood product manufacturing",
  "Aluminum product manufacturing from purchased aluminum + Alumina refining and primary aluminum production + Secondary smelting and alloying of aluminum",
  "Ammunition, arms, ordnance, and accessories manufacturing",
  "Amusement parks and arcades",
  "Analytical laboratory instrument manufacturing",
  "Animal (except poultry) slaughtering, rendering, and processing",
  "Animal production, except cattle and poultry and eggs",
  "Apparel manufacturing",
  "Architectural, engineering, and related services",
  "Asphalt paving mixture and block manufacturing",
  "Asphalt shingle and coating materials manufacturing",
  "Audio and video equipment manufacturing",
  "Automatic environmental control manufacturing",
  "Automobile manufacturing",
  "Automotive equipment rental and leasing",
  "Automotive repair and maintenance",
  "Ball and roller bearing manufacturing",
  "Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",
  "Biological product (except diagnostic) manufacturing",
  "Boat building",
  "Book publishers",
  "Bread and bakery product manufacturing",
  "Breakfast cereal manufacturing",
  "Breweries",
  "Broadcast and wireless communications equipment",
  "Building material and garden equipment and supplies dealers",
  "Business support services",
  "Cable and other subscription programming",
  "Carbon and graphite product manufacturing",
  "Carpet and rug mills",
  "Cement manufacturing",
  "Cheese manufacturing",
  "Child day care services",
  "Civic, social, professional, and similar organizations",
  "Clay product and refractory manufacturing",
  "Clothing and clothing accessories stores",
  "Coal mining",
  "Coating, engraving, heat treating and allied activities",
  "Coffee and tea manufacturing",
  "Commercial and industrial machinery and equipment rental and leasing",
  "Commercial and industrial machinery and equipment repair and maintenance",
  "Communication and energy wire and cable manufacturing",
  "Community food, housing, and other relief services, including rehabilitation services",
  "Computer storage device manufacturing",
  "Computer systems design services",
  "Computer terminals and other computer peripheral equipment manufacturing",
  "Concrete pipe, brick, and block manufacturing",
  "Construction machinery manufacturing",
  "Cookie, cracker, pasta, and tortilla manufacturing",
  "Copper rolling, drawing, extruding and alloying",
  "Copper, nickel, lead, and zinc mining",
  "Couriers and messengers",
  "Curtain and linen mills",
  "Custom computer programming services",
  "Custom roll forming",
  "Customs duties",
  "Cut stone and stone product manufacturing",
  "Cutlery and handtool manufacturing",
  "Cutting and machine tool accessory, rolling mill, and other metalworking machinery manufacturing",
  "Dairy cattle and milk production",
  "Data processing, hosting, and related services",
  "Death care services",
  "Dental equipment and supplies manufacturing",
  "Dental laboratories",
  "Direct life insurance carriers",
  "Directory, mailing list, and other publishers",
  "Distilleries",
  "Dog and cat food manufacturing",
  "Doll, toy, and game manufacturing",
  "Drilling oil and gas wells",
  "Drugs and druggists’ sundries",
  "Dry, condensed, and evaporated dairy product manufacturing",
  "Dry-cleaning and laundry services",
  "Educational and vocational structures",
  "Electric lamp bulb and part manufacturing",
  "Electric power generation, transmission, and distribution",
  "Electricity and signal testing instruments manufacturing",
  "Electromedical and electrotherapeutic apparatus manufacturing",
  "Electronic and precision equipment repair and maintenance",
  "Electronic computer manufacturing",
  "Elementary and secondary schools",
  "Employment services",
  "Environmental and other technical consulting services",
  "Fabric mills",
  "Fabricated pipe and pipe fitting manufacturing",
  "Facilities support services",
  "Farm machinery and equipment manufacturing",
  "Fats and oils refining and blending",
  "Federal general government (defense)",
  "Federal general government (nondefense)",
  "Ferrous metal foundries",
  "Fertilizer manufacturing",
  "Fiber, yarn, and thread mills",
  "Fishing, hunting and trapping",
  "Flavoring syrup and concentrate manufacturing",
  "Flour milling and malt manufacturing",
  "Fluid milk and butter manufacturing",
  "Fluid power process machinery",
  "Food and beverage stores",
  "Forestry and logging",
  "Frozen food manufacturing",
  "Fruit and tree nut farming",
  "Fruit and vegetable canning, pickling, and drying",
  "Full-service restaurants",
  "Funds, trusts, and other financial vehicles",
  "Gambling industries (except casino hotels)",
  "Gasoline stations",
  "General and consumer goods rental",
  "General merchandise stores",
  "Glass and glass product manufacturing",
  "Grain farming",
  "Grantmaking, giving, and social advocacy organizations",
  "Greenhouse, nursery, and floriculture production",
  "Grocery and related product wholesalers",
  "Ground or treated mineral and earth manufacturing",
  "Guided missile and space vehicle manufacturing",
  "Hardware manufacturing",
  "Health and personal care stores",
  "Health care structures",
  "Heating equipment (except warm air furnaces) manufacturing",
  "Heavy duty truck manufacturing",
  "Home health care services",
  "Hospitals",
  "Household appliances and electrical and electronic goods",
  "Household cooking appliance manufacturing",
  "Household laundry equipment manufacturing",
  "Household refrigerator and home freezer manufacturing",
  "Ice cream and frozen dessert manufacturing",
  "In-vitro diagnostic substance manufacturing",
  "Independent artists, writers, and performers",
  "Individual and family services",
  "Industrial and commercial fan and blower and air purification equipment manufacturing",
  "Industrial gas manufacturing",
  "Industrial mold manufacturing",
  "Industrial process furnace and oven manufacturing",
  "Industrial process variable instruments manufacturing",
  "Institutional furniture manufacturing",
  "Insurance agencies, brokerages, and related activities",
  "Insurance carriers, except direct life",
  "Internet publishing and broadcasting and Web search portals",
  "Investigation and security services",
  "Iron and steel mills and ferroalloy manufacturing",
  "Iron, gold, silver, and other metal ore mining",
  "Irradiation apparatus manufacturing",
  "Jewelry and silverware manufacturing",
  "Junior colleges, colleges, universities, and professional schools",
  "Laminated plastics plate, sheet (except packaging), and shape manufacturing",
  "Lawn and garden equipment manufacturing",
  "Leather and allied product manufacturing",
  "Legal services",
  "Lessors of nonfinancial intangible assets",
  "Light truck and utility vehicle manufacturing",
  "Lighting fixture manufacturing",
  "Lime and gypsum product manufacturing",
  "Limited-service restaurants",
  "Machine shops",
  "Machine tool manufacturing",
  "Machinery, equipment, and supplies",
  "Management consulting services",
  "Management of companies and enterprises",
  "Manufacturing and reproducing magnetic and optical media",
  "Manufacturing structures",
  "Material handling equipment manufacturing",
  "Measuring, dispensing, and other pumping equipment manufacturing",
  "Mechanical power transmission equipment manufacturing",
  "Medical and diagnostic laboratories",
  "Medicinal and botanical manufacturing",
  "Metal can, box, and other metal container (light gauge) manufacturing",
  "Metal crown, closure, and other metal stamping (except automotive)",
  "Metal tank (heavy gauge) manufacturing",
  "Military armored vehicle, tank, and tank component manufacturing",
  "Millwork",
  "Mineral wool manufacturing",
  "Mining and oil and gas field machinery manufacturing",
  "Miscellaneous nonmetallic mineral products",
  "Monetary authorities and depository credit intermediation",
  "Motion picture and video industries",
  "Motor and generator manufacturing",
  "Motor home manufacturing",
  "Motor vehicle and motor vehicle parts and supplies",
  "Motor vehicle and parts dealers",
  "Motor vehicle body manufacturing",
  "Motor vehicle electrical and electronic equipment manufacturing",
  "Motor vehicle gasoline engine and engine parts manufacturing",
  "Motor vehicle metal stamping",
  "Motor vehicle seating and interior trim manufacturing",
  "Motor vehicle steering, suspension component (except spring), and brake systems manufacturing",
  "Motor vehicle transmission and power train parts manufacturing",
  "Motorcycle, bicycle, and parts manufacturing",
  "Multifamily residential structures",
  "Museums, historical sites, zoos, and parks",
  "Natural gas distribution",
  "News syndicates, libraries, archives and all other information services",
  "Newspaper publishers",
  "Nondepository credit intermediation and related activities",
  "Nonferrous Metal (except Aluminum) Smelting and Refining",
  "Nonferrous metal (except copper and aluminum) rolling, drawing, extruding and alloying",
  "Nonferrous metal foundries",
  "Nonresidential maintenance and repair",
  "Nonstore retailers",
  "Nonupholstered wood household furniture manufacturing",
  "Nursing and community care facilities",
  "Office administrative services",
  "Office and commercial structures",
  "Office furniture and custom architectural woodwork and millwork manufacturing",
  "Office supplies (except paper) manufacturing",
  "Offices of dentists",
  "Offices of other health practitioners",
  "Offices of physicians",
  "Oil and gas extraction",
  "Oilseed farming",
  "Ophthalmic goods manufacturing",
  "Optical instrument and lens manufacturing",
  "Ornamental and architectural metal products manufacturing",
  "Other Basic Inorganic Chemical Manufacturing",
  "Other Motor Vehicle Parts Manufacturing",
  "Other aircraft parts and auxiliary equipment manufacturing",
  "Other ambulatory health care services",
  "Other amusement and recreation industries",
  "Other animal food manufacturing",
  "Other basic organic chemical manufacturing",
  "Other commercial and service industry machinery manufacturing",
  "Other communications equipment manufacturing",
  "Other computer related services, including facilities management",
  "Other concrete product manufacturing",
  "Other crop farming",
  "Other durable goods merchant wholesalers",
  "Other educational services",
  "Other electronic component manufacturing",
  "Other engine equipment manufacturing",
  "Other fabricated metal manufacturing",
  "Other federal government enterprises",
  "Other financial investment activities",
  "Other furniture related product manufacturing",
  "Other general purpose machinery manufacturing",
  "Other household nonupholstered furniture",
  "Other industrial machinery manufacturing",
  "Other major household appliance manufacturing",
  "Other nondurable goods merchant wholesalers",
  "Other nonmetallic mineral mining and quarrying",
  "Other nonresidential structures",
  "Other personal services",
  "Other petroleum and coal products manufacturing",
  "Other plastics product manufacturing",
  "Other real estate",
  "Other residential structures",
  "Other rubber product manufacturing",
  "Other state and local government enterprises",
  "Other support activities for mining",
  "Other support services",
  "Other textile product mills",
  "Outpatient care centers",
  "Owner-occupied housing",
  "Packaging machinery manufacturing",
  "Paint and coating manufacturing",
  "Paper Bag and Coated and Treated Paper Manufacturing",
  "Paper mills",
  "Paperboard container manufacturing",
  "Paperboard mills",
  "Performing arts companies",
  "Periodical Publishers",
  "Personal and household goods repair and maintenance",
  "Personal care services",
  "Pesticide and other agricultural chemical manufacturing",
  "Petrochemical manufacturing",
  "Petroleum and petroleum products",
  "Petroleum refineries",
  "Pharmaceutical preparation manufacturing",
  "Photographic and photocopying equipment manufacturing",
  "Photographic services",
  "Pipeline transportation",
  "Plastics bottle manufacturing",
  "Plastics material and resin manufacturing",
  "Plastics packaging materials and unlaminated film and sheet manufacturing",
  "Plastics pipe, pipe fitting, and unlaminated profile shape manufacturing",
  "Plate work and fabricated structural product manufacturing",
  "Plumbing fixture fitting and trim manufacturing",
  "Polystyrene foam product manufacturing",
  "Postal service",
  "Poultry and egg production",
  "Poultry processing",
  "Power and communication structures",
  "Power boiler and heat exchanger manufacturing",
  "Power, distribution, and specialty transformer manufacturing",
  "Power-driven handtool manufacturing",
  "Primary battery manufacturing",
  "Printed circuit assembly (electronic assembly) manufacturing",
  "Printing",
  "Printing ink manufacturing",
  "Private households",
  "Professional and commercial equipment and supplies",
  "Promoters of performing arts and sports and agents for public figures",
  "Propulsion units and parts for space vehicles and guided missiles",
  "Pulp mills",
  "Radio and television broadcasting",
  "Rail transportation",
  "Railroad rolling stock manufacturing",
  "Ready-mix concrete manufacturing",
  "Relay and industrial control manufacturing",
  "Religious organizations",
  "Residential maintenance and repair",
  "Residential mental health, substance abuse, and other residential care facilities",
  "Rubber and plastics hoses and belting manufacturing",
  "Sanitary paper product manufacturing",
  "Satellite, telecommunications resellers, and all other telecommunications",
  "Sawmills and wood preservation",
  "Scenic and sightseeing transportation and support activities for transportation",
  "Scientific research and development services",
  "Seafood product preparation and packaging",
  "Search, detection, and navigation instruments manufacturing",
  "Seasoning and dressing manufacturing",
  "Securities and commodity contracts intermediation and brokerage",
  "Semiconductor and related device manufacturing",
  "Semiconductor machinery manufacturing",
  "Services to buildings and dwellings",
  "Ship building and repairing",
  "Showcase, partition, shelving, and locker manufacturing",
  "Sign manufacturing",
  "Single-family residential structures",
  "Small electrical appliance manufacturing",
  "Snack food manufacturing",
  "Soap and cleaning compound manufacturing",
  "Soft drink and ice manufacturing",
  "Software publishers",
  "Sound recording industries",
  "Soybean and other oilseed processing",
  "Special tool, die, jig, and fixture manufacturing",
  "Specialized design services",
  "Spectator sports",
  "Speed changer, industrial high-speed drive, and gear manufacturing",
  "Sporting and athletic goods manufacturing",
  "Spring and wire product manufacturing",
  "State and local government educational services",
  "State and local government hospitals and health services",
  "State and local government other services",
  "Stationery product manufacturing",
  "Steel product manufacturing from purchased steel",
  "Stone mining and quarrying",
  "Storage battery manufacturing",
  "Sugar and confectionery product manufacturing",
  "Support activities for agriculture and forestry",
  "Support activities for printing",
  "Surgical and medical instrument manufacturing",
  "Surgical appliance and supplies manufacturing",
  "Switchgear and switchboard apparatus manufacturing",
  "Synthetic dye and pigment manufacturing",
  "Synthetic rubber and artificial and synthetic fibers and filaments manufacturing",
  "Telephone apparatus manufacturing",
  "Tenant-occupied housing",
  "Textile and fabric finishing and fabric coating mills",
  "Tire manufacturing",
  "Tobacco product manufacturing",
  "Toilet preparation manufacturing",
  "Totalizing fluid meter and counting device manufacturing",
  "Transit and ground passenger transportation + State and local government passenger transit",
  "Transportation structures and highways and streets",
  "Travel arrangement and reservation services",
  "Travel trailer and camper manufacturing",
  "Truck trailer manufacturing",
  "Truck transportation",
  "Turbine and turbine generator set units manufacturing",
  "Turned product and screw, nut, and bolt manufacturing",
  "Upholstered household furniture manufacturing",
  "Urethane and other foam product (except polystyrene) manufacturing",
  "Valve and fittings other than plumbing",
  "Vegetable and melon farming",
  "Veneer, plywood, and engineered wood product manufacturing",
  "Veterinary services",
  "Warehousing and storage",
  "Waste management and remediation services",
  "Watch, clock, and other measuring and controlling device manufacturing",
  "Water transportation",
  "Water, sewage and other systems",
  "Wet corn milling",
  "Wholesale electronic markets and agents and brokers",
  "Wineries",
  "Wired telecommunications carriers",
  "Wireless telecommunications carriers (except satellite)",
  "Wiring device manufacturing",
  "Wood kitchen cabinet and countertop manufacturing"
] as const;

export type CedaCategory = typeof cedaCategories[number];
